# Config file for aftcode2_0 created by Benjamin Simpson on 3/19/2026 for Capstone II in Spring 2026

# This file will contain parameters for MPC_Y_Solver.py, MPC_X_Solver.py, computer_vision.py, and, if time permits, the velocity control codes found on the raspberry pi.

# Credit to Aashish Kumar for writing a Medium article explaining how to create config files:
# https://medium.com/the-pythonworld/how-to-write-and-use-configuration-files-in-python-like-a-pro-8465126ca055

# Important Note: The current solver scripts rely on arguments being passed through terminal for config.
#  to get around this, add a 'flag' in 'config.yaml' that signals to the solver if it should take terminal inputs #  or read from the config. file.

# Table measurements (in meters) for PROTOTYPE 1
# Approximate player foot diameters is a rough approximation of the diameter of the players foot if it were a circle
table_measurements:
  field_height: 0.340
  field_width: 0.590
  player_length: 0.045 # foot to torso
  distance_between_players: 0.090 # center neck to center neck
  player_distance_from_wall: 0.030
  distance_to_clear_zone: 0.100 # distance that the first player travels across the field when given full steps
  blue_rod_positions: # from left of field to right of field (facing away from hardware)
    rod_one: 0.068
    rod_two: -1
    rod_three: 0.435
  approximate_player_foot_diameter: 0.015
  ball_diameter: 0.030
  steps_per_revolution: 400
  steps_across_field: 525
  
# Camera parameters
camera_parameters:
  frame_rate: 60
  warp_points: # a list of lists 'pts1 = np.float32([[25,7],[616,12],[23,351],[618,352]])'
    - [25,7]
    - [616,12]
    - [23,351]
    - [618,352]
  
# Y Solver parameters
y_solver_parameters:
  timestep: 0.0166667 # seconds
  max_input: 31 # rad/sec (converted to meters per second in solver)
  prediction_steps: 2
  input_rate_weight: 0.2
  cost_function:
    input_weight: 0
    position_error_weight: 50
    velocity_error_weight: 15
    
# X Solver parameters
x_solver_parameters:
  timestep: 0.0166667 # seconds
  max_input: 31 # radians/sec
  prediction_steps: 2
  input_rate_weight: 0.2
  cost_function:
    input_weight: 0.2
    resting_weight: 20
    position_error_weight: 0
    velocity_error_weight: 15
    goal_error_weight: 0
  collision_gain_type: 1  
  
# Motor parameters (TBD)

# Faulty Measurements 

#--zero (O)--
#layout: 
#  dim: []
#  data_offset: 0
#data: [0.0, 0.09, 0.18]
#---

#--final (X)--
#layout: 
#  dim: []
#  data_offset: 0
#data: [0.1133333, 0.2033333, 0.2933333]
#---


#--------O--------   -> 0.00                     
#|       |
#|       |
#|       |                
#|       | 
#|       |
#|       |  
#|       |
#|       |
#|       O -> 0.09
#|       |
#|       X -> 0.11
#|       | 
#|       |
#|       |
#|       |
#|       |
#|       |
#|       O -> 0.18
#|       |
#|       X -> 0.20
#|       |
#|       | 
#|       |
#|       |
#|       |
#|       |
#|       |
#|       |
#|       X -> 0.29
#|       | 
#|       | 
#|       | 
#|       | 
#|       |
#-----------------         

# Real World Positions

# Zero (*)
# Final (@)

#-----------------       
#|       |
#|       |
#|       * -> 0.03               
#|       | 
#|       |
#|       |  
#|       |
#|       |
#|       |
#|       |
#|       |
#|       * -> 0.03 + 0.09 = 0.12
#|       |
#|       @ -> 
#|       |
#|       |
#|       |
#|       | 
#|       |
#|       |
#|       * -> 0.12 + 0.09 = 0.21
#|       | 
#|       @
#|       |
#|       |
#|       |
#|       |
#|       |
#|       |
#|       | -> 0.
#|       | 
#|       @ 
#|       | -> 0.33
#|       |
#-----------------             
